/*
 * @Author: chengmac 
 * @Date: 2018-10-17 20:55:52 
 * @Last Modified by: chengmac
 * @Last Modified time: 2019-05-30 21:29:13
 */

// 登录模块
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_REQUEST_SUCCESS = 'LOGIN_REQUEST_SUCCESS';
export const LOGIN_REQUEST_FAILURE = 'LOGIN_REQUEST_FAILURE';

// 文档模块
export const ARTICLE_SAVE = 'ARTICLE_SAVE';
export const ARTICLE_SAVE_SUCCESS = 'ARTICLE_SAVE_SUCCESS';
export const ARTICLE_SAVE_FAILURE = 'ARTICLE_SAVE_FAILURE';

export const GET_ARTICLE = 'GET_ARTICLE';
export const GET_ARTICLE_SUCCESS = 'GET_ARTICLE_SUCCESS';
export const GET_ARTICLE_FAILURE = 'GET_ARTICLE_FAILURE';

export const GET_ARTICLE_LIST = 'GET_ARTICLE_LIST';
export const GET_ARTICLE_LIST_SUCCESS = 'GET_ARTICLE_LIST_SUCCESS';
export const GET_ARTICLE_LIST_FAILURE = 'GET_ARTICLE_LIST_FAILURE';

export const DELETE_ARTICLE = 'DELETE_ARTICLE';
export const DELETE_ARTICLE_SUCCESS = 'DELETE_ARTICLE_SUCCESS';
export const DELETE_ARTICLE_FAILURE = 'DELETE_ARTICLE_FAILURE';

export const UPLOAD_ARTICLE_IMAGE = 'UPLOAD_ARTICLE_IMAGE';
export const UPLOAD_ARTICLE_IMAGE_SUCCESS = 'UPLOAD_ARTICLE_IMAGE_SUCCESS';
export const UPLOAD_ARTICLE_IMAGE_FAILURE = 'UPLOAD_ARTICLE_IMAGE_FAILURE';

// 菜单栏
export const MENU_LIST = 'MENU_LIST';
export const MENU_ROUTER_JUMP = 'MENU_ROUTER_JUMP';

// 消息提示
export const NEWS_LIST = 'NEWS_LIST';
export const NEWS_LIST_SUCCESS = 'NEWS_LIST_SUCCESS';
export const NEWS_LIST_FAILURE = 'NEWS_LIST_FAILURE';

// 更改消息为已读
export const UPDATE_NEWS_STATUS = 'UPDATE_NEWS_STATUS';
export const UPDATE_NEWS_STATUS_SUCCESS = 'UPDATE_NEWS_STATUS_SUCCESS';
export const UPDATE_NEWS_STATUS_FAILURE = 'UPDATE_NEWS_STATUS_FAILURE';

// 分类
export const GET_ARTICLE_CLASSIFY = 'GET_ARTICLE_CLASSIFY';
// 标签
export const GET_ARTICLE_lABEL = 'GET_ARTICLE_lABEL';